FROM jenkins/jenkins
USER root
RUN curl https://raw.githubusercontent.com/sergio-rosendo-code/Jenkins-Pipeline/clean-repo/Docker.Jenkins/Installation.Tools/tools.sh | bash
RUN curl https://raw.githubusercontent.com/sergio-rosendo-code/Jenkins-Pipeline/clean-repo/Docker.Jenkins/Installation.Tools/dotnet7.sh | bash
RUN curl https://raw.githubusercontent.com/sergio-rosendo-code/Jenkins-Pipeline/clean-repo/Docker.Jenkins/Installation.Tools/azure.sh | bash
