FROM jenkins/jenkins
USER root
RUN curl https://raw.githubusercontent.com/sergio-rosendo-code/Jenkins-Pipeline/main/Docker/tools.sh | bash
RUN curl https://raw.githubusercontent.com/sergio-rosendo-code/Jenkins-Pipeline/main/Docker/dotnet7.sh | bash
RUN curl https://raw.githubusercontent.com/sergio-rosendo-code/Jenkins-Pipeline/main/Docker/docker.sh | bash
